.
./sync_ai.py
./frontend
./frontend/app
./frontend/app/settings
./frontend/app/settings/page.tsx
./frontend/app/favicon.ico
./frontend/app/dashboard
./frontend/app/dashboard/page.tsx
./frontend/app/trends
./frontend/app/trends/page.tsx
./frontend/app/review
./frontend/app/review/[id]
./frontend/app/review/[id]/page.tsx
./frontend/app/layout.tsx
./frontend/app/page.tsx
./frontend/app/globals.css
./frontend/postcss.config.mjs
./frontend/next-env.d.ts
./frontend/README.md
./frontend/components
./frontend/components/Navbar.tsx
./frontend/components/TrendProductCard.tsx
./frontend/components/FileUpload.tsx
./frontend/public
./frontend/public/file.svg
./frontend/public/vercel.svg
./frontend/public/next.svg
./frontend/public/globe.svg
./frontend/public/window.svg
./frontend/package-lock.json
./frontend/package.json
./frontend/lib
./frontend/lib/api.ts
./frontend/tsconfig.json
./frontend/AGENTS.md
./frontend/eslint.config.mjs
./frontend/next.config.ts
./backend
./backend/run.py
./backend/app
./backend/app/routers
./backend/app/routers/scraper.py
./backend/app/routers/creations.py
./backend/app/routers/health.py
./backend/app/routers/__init__.py
./backend/app/routers/etsy.py
./backend/app/routers/pipeline.py
./backend/app/routers/settings.py
./backend/app/models.py
./backend/app/database.py
./backend/app/__init__.py
./backend/app/schemas.py
./backend/app/main.py
./backend/app/services
./backend/app/services/etsy_api.py
./backend/app/services/dalle_image.py
./backend/app/services/scraper.py
./backend/app/services/vector.py
./backend/app/services/export_formats.py
./backend/app/services/compliance.py
./backend/app/services/svg_analyzer.py
./backend/app/services/gemini_seo.py
./backend/app/services/generator.py
./backend/app/services/mockup_processor.py
./backend/app/services/image.py
./backend/requirements.txt
./backend/tests
./backend/tests/test_app.py
./backend/assets
./backend/assets/backgrounds
./backend/etsy_laser_auto.db
./project_structure.txt
./README.md
./etsy_laser_auto.db

